version: "3"  # composeファイルのバージョンを指定する
services:       # このレイヤーの配下にコンテナ単位で記述を追加していく
###########ここからAppサーバの設定###########
    app-server:   # サービスの名前、ホスト名にもなりうる
        container_name: app-server  # コンテナの名前
        build:                      # 自分で用意したDockerfileでビルドを行う場合必要なブロック
            context: ../../         # docker buildするときのパスを指定、ymlファイルのあるところからの相対パス
            dockerfile: deployment/dockerfiles/app-server/Dockerfile # 利用するDockerfile。contextのパスから指定
        networks:                   # このサービスが属するネットワークの設定
            my_host_network:        # 後述のmy_host_networkに属する
                aliases:
                    - uwsgi-server  # my_host_network上ではこの名前で判別できるようになる
        expose:
            - 9876                  # このポートをLISTEN状態にする
        restart: always             # サービス再起動ポリシー
###########ここまでAppサーバの設定###########
###########ここからWebサーバの設定###########
    web-server:
        container_name: web-server
        build:
            context: ../../
            dockerfile: deployment/dockerfiles/web-server/Dockerfile
        networks:
            my_host_network:
                aliases:
                    - nginx-server
        ports:
            - 9090:9123     # ホストPCの9090番をコンテナの9123番にポートフォワーディング
        depends_on:         # 依存関係を指定。web-serverの起動より前にapp-serverを起動するようになる
            - app-server
        restart: always
###########ここまでWebサーバの設定###########

###########ここからネットワークの設定###########
networks:
    my_host_network:            # 上の方のサーバ設定で使うときのエイリアス名
        name: my-nginx-network  # ネットワークの名前
        driver: bridge          # ドライバ種別、bridgeかoverlay